version: "3.8"
services:
  backend:
    image: "sow4063/springboot-react-fullstack:5.7.2022.0.0.8"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev